#! /usr/bin/env bash

set -eu -o pipefail

#
# Run the update.lambda_handler locally in a docker container
#

docker build -t local-antivirus-lambda:latest .

NAME="antivirus-update"
trap "docker stop ${NAME}" EXIT ERR INT TERM
docker run --rm \
  -p 9000:8080 \
  -e AV_DEFINITION_PATH \
  -e AV_DEFINITION_S3_BUCKET \
  -e AV_DEFINITION_S3_PREFIX \
  -e AWS_ACCESS_KEY_ID \
  -e AWS_DEFAULT_REGION \
  -e AWS_REGION \
  -e AWS_SECRET_ACCESS_KEY \
  -e AWS_SESSION_TOKEN \
  -e CLAMAVLIB_PATH \
  --memory="${MEM}" \
  --memory-swap="${MEM}" \
  --cpus="${CPUS}" \
  --name="${NAME}" \
  -d \
  local-antivirus-lambda:latest update.lambda_handler

until [ "`docker inspect -f {{.State.Running}} ${NAME}`"=="true" ]; do
    sleep 0.1;
done;

curl -XPOST "http://localhost:9000/2015-03-31/functions/function/invocations" -d "{}" &
docker logs ${NAME} -f